"""Add username column to users table

Revision ID: 61c621b69dc1
Revises: 2e8d3bb0fa46
Create Date: 2024-08-15 15:11:20.487713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = '61c621b69dc1'
down_revision: Union[str, None] = '2e8d3bb0fa46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_table = table('users',
                   column('email', sa.String),
                   column('username', sa.String),
                   )

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.execute(
        user_table.update().values(
            username=sa.func.substr(user_table.c.email, 1, sa.func.length(user_table.c.email) - 10)
        ).where(user_table.c.email.like('%@gmail.com'))
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    pass
    # ### end Alembic commands ###
